import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Build from './components/build'
import Digit from './components/digit'
import Feature from './components/feature'
import Find from './components/find'
import Hero from './components/hero'
import Navbar from './components/navbar'

export default function Home() {
  
  return (

    <div className=''>
      <Head> 
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-curve'>
        <div className='hero'>
        <Navbar />
        <Hero />
        </div>
      </div>
      <Feature /> 
      <Find />
      <div className='bg-build'>
        <div className='bg-line'>
          <Build />
        </div>
        
      </div>
      <Digit />
      
        <div className='bg-globe p-b-100 '>
          <section className='bg-dig'>
            
          </section>
        </div>
      
    </div>
  )
}
